In [115]:
#this code is given by anushka
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [116]:
# input dataset
X = np.array([
                [0,0,1],
                [0,1,0],
                [0,1,1],
                [1,0,0],
                [1,0,1],
                [1,1,0],
                ])
          
y = np.array([1,1,0,1,0,0])

In [117]:
#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train=X
y_train=y

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


In [118]:
import keras
from keras.models import Sequential #to initialise neural network
from keras.layers import Dense #to build layers


In [128]:
classifier = Sequential()
classifier.add(Dense(output_dim = 6,  activation = 'relu', input_dim = 3)) #11 independent variables
classifier.add(Dense(output_dim = 6,  activation = 'relu')) #11 independent variables
classifier.add(Dense(output_dim = 1,  activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 3, nb_epoch = 400)



c:\users\dell\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", input_dim=3)`
  
c:\users\dell\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\dell\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid")`
  after removing the cwd from sys.path.
c:\users\dell\appdata\local\programs\python\python35\lib\site-packages\keras\models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/400
6/6 [==============================] - 2s 363ms/step - loss: 0.6433 - acc: 0.6667
Epoch 2/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6423 - acc: 0.6667
Epoch 3/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6413 - acc: 0.6667
Epoch 4/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6405 - acc: 0.6667
Epoch 5/400
6/6 [==============================] - 0s 3ms/step - loss: 0.6396 - acc: 0.6667
Epoch 6/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6389 - acc: 0.6667
Epoch 7/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6380 - acc: 0.6667
Epoch 8/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6372 - acc: 0.6667
Epoch 9/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6362 - acc: 0.6667
Epoch 10/400
6/6 [==============================] - 0s 2ms/step - loss: 0.6356 - acc: 0.6667
Epoch 11/400
6/6 [==============================] - 0s 2ms/step - loss: 0.634

6/6 [==============================] - 0s 2ms/step - loss: 0.5403 - acc: 0.8333
Epoch 90/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5392 - acc: 0.8333
Epoch 91/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5378 - acc: 0.8333
Epoch 92/400
6/6 [==============================] - 0s 1ms/step - loss: 0.5363 - acc: 0.8333
Epoch 93/400
6/6 [==============================] - 0s 1ms/step - loss: 0.5349 - acc: 0.8333
Epoch 94/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5335 - acc: 0.8333
Epoch 95/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5324 - acc: 0.8333
Epoch 96/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5307 - acc: 0.8333
Epoch 97/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5294 - acc: 0.8333
Epoch 98/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5283 - acc: 0.8333
Epoch 99/400
6/6 [==============================] - 0s 2ms/step - loss: 0.5267 - ac

6/6 [==============================] - 0s 2ms/step - loss: 0.4176 - acc: 0.8333
Epoch 177/400
6/6 [==============================] - 0s 3ms/step - loss: 0.4162 - acc: 0.8333
Epoch 178/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4148 - acc: 0.8333
Epoch 179/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4134 - acc: 0.8333
Epoch 180/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4119 - acc: 0.8333
Epoch 181/400
6/6 [==============================] - 0s 3ms/step - loss: 0.4107 - acc: 0.8333
Epoch 182/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4087 - acc: 0.8333
Epoch 183/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4076 - acc: 0.8333
Epoch 184/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4060 - acc: 0.8333
Epoch 185/400
6/6 [==============================] - 0s 2ms/step - loss: 0.4045 - acc: 0.8333
Epoch 186/400
6/6 [==============================] - 0s 2ms/step - loss: 0

6/6 [==============================] - 0s 2ms/step - loss: 0.3010 - acc: 0.8333
Epoch 262/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2996 - acc: 0.8333
Epoch 263/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2983 - acc: 0.8333
Epoch 264/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2971 - acc: 0.8333
Epoch 265/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2961 - acc: 0.8333
Epoch 266/400
6/6 [==============================] - 0s 1ms/step - loss: 0.2946 - acc: 0.8333
Epoch 267/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2938 - acc: 0.8333
Epoch 268/400
6/6 [==============================] - 0s 3ms/step - loss: 0.2922 - acc: 0.8333
Epoch 269/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2911 - acc: 0.8333
Epoch 270/400
6/6 [==============================] - 0s 3ms/step - loss: 0.2897 - acc: 0.8333
Epoch 271/400
6/6 [==============================] - 0s 2ms/step - loss: 0

6/6 [==============================] - 0s 2ms/step - loss: 0.2048 - acc: 1.0000
Epoch 348/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2041 - acc: 1.0000
Epoch 349/400
6/6 [==============================] - 0s 4ms/step - loss: 0.2030 - acc: 1.0000
Epoch 350/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2022 - acc: 1.0000
Epoch 351/400
6/6 [==============================] - 0s 2ms/step - loss: 0.2010 - acc: 1.0000
Epoch 352/400
6/6 [==============================] - 0s 2ms/step - loss: 0.1999 - acc: 1.0000
Epoch 353/400
6/6 [==============================] - 0s 2ms/step - loss: 0.1991 - acc: 1.0000
Epoch 354/400
6/6 [==============================] - ETA: 0s - loss: 0.2787 - acc: 1.000 - 0s 2ms/step - loss: 0.1982 - acc: 1.0000
Epoch 355/400
6/6 [==============================] - 0s 3ms/step - loss: 0.1973 - acc: 1.0000
Epoch 356/400
6/6 [==============================] - 0s 2ms/step - loss: 0.1963 - acc: 1.0000
Epoch 357/400
6/6 [=================

In [127]:
y_pred = classifier.predict(np.array([[0,0,1]]))
print(y_pred)

[[0.5556756]]
